; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Tikfinity-GZDoom"
#define MyAppVersion "1.4"
#define MyAppPublisher "Jeremy Tiggy"
#define MyAppURL "https://github.com/jeremytiggy/Tikfinity-GZDoom"
#define MyAppExeName "TikFinity-GZDoom.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3252A7B9-C2D3-491B-A8DA-8DC654D60290}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
LicenseFile=C:\dev\JeremyTiggy GitHub Repositories\Powershell-GZDoom_REST\LICENSE
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=C:\dev\JeremyTiggy GitHub Repositories\Powershell-GZDoom_REST\Releases\Install Scripts
OutputBaseFilename=Tikfinity-GZDoom_v{#MyAppVersion}
SetupIconFile=C:\dev\JeremyTiggy GitHub Repositories\Powershell-GZDoom_REST\Source\example\Icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\dev\JeremyTiggy GitHub Repositories\Powershell-GZDoom_REST\Releases\v{#MyAppVersion}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\JeremyTiggy GitHub Repositories\Powershell-GZDoom_REST\Releases\v{#MyAppVersion}\GZDoom_REST_API_Actions_v*.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dev\JeremyTiggy GitHub Repositories\Powershell-GZDoom_REST\Releases\v{#MyAppVersion}\lib\*"; DestDir: "{app}\lib\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\dev\JeremyTiggy GitHub Repositories\Powershell-GZDoom_REST\Releases\v{#MyAppVersion}\gzdoom-4-14-2-windows-External-Pipe\*"; DestDir: "{app}\gzdoom-4-14-2-windows-External-Pipe\"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{autodesktop}\GZDoom External Pipe v4.14.2"; Filename: "{app}\gzdoom-4-14-2-windows-External-Pipe\gzdoom.exe"; Tasks: desktopicon

