; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "TikFinity-GZDoom"
#define MyAppVersion "2.4"
#define MyAppPublisher "Jeremy Tiggy"
#define MyAppURL "Https://github.com/JeremyTiggy/TikFinity-GZDoom"
#define MyAppExeName "TikFinity-GZDoom.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4C67AB69-C622-40B5-875A-1DA1C050A825}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AllowRootDirectory=yes
CreateAppDir=yes
AlwaysShowDirOnReadyPage=yes
DisableDirPage=yes
DefaultDirName={sd}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
AlwaysShowGroupOnReadyPage=yes
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\j.tighe\Documents\GitHub\Tikfinity-GZDoom\src\installer
OutputBaseFilename=TikFinity-GZDoom Installer
SetupIconFile=C:\Users\j.tighe\Documents\GitHub\Tikfinity-GZDoom\src\graphics\Icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "C:\Users\j.tighe\Documents\GitHub\Tikfinity-GZDoom\build\Program Folder\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\j.tighe\Documents\GitHub\Tikfinity-GZDoom\build\Program Folder\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{group}\DoomRunner (Tikfinity-GZDoom)"; Filename: "{app}\GZDoom\DoomRunner.exe"
Name: "{group}\TikFinity-GZDoom Program Folder"; Filename: "{app}"
Name: "{group}\Quick Start Guide"; Filename: "{app}\info\TikFinity-GZDoom Interface Script Quick Start Guide.pdf"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{autodesktop}\DoomRunner (Tikfinity-GZDoom)"; Filename: "{app}\GZDoom\DoomRunner.exe"; Tasks: desktopicon
Name: "{autodesktop}\TikFinity-GZDoom Program Folder"; Filename: "{app}"; Tasks: desktopicon
