; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "TikFinity-ZDoom"
#define MyAppVersion "2.5"
#define MyAppPublisher "Jeremy Tiggy"
#define MyAppURL "Https://github.com/JeremyTiggy/TikFinity-GZDoom"
#define MyAppExeName "TikFinity-ZDoom.bat"
#define MyAppLocalRepository "C:\Users\j.tighe\Documents\GitHub\Tikfinity-GZDoom"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4C67AB69-C622-40B5-875A-1DA1C050A825}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AllowRootDirectory=yes
CreateAppDir=yes
AlwaysShowDirOnReadyPage=yes
DisableDirPage=yes
DefaultDirName={sd}\{#MyAppName}
UninstallDisplayIcon={app}\graphics\{#MyAppName}.ico
DisableProgramGroupPage=yes
AlwaysShowGroupOnReadyPage=yes
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#MyAppLocalRepository}\src\installer
OutputBaseFilename={#MyAppName} Installer
SetupIconFile={#MyAppLocalRepository}\src\graphics\{#MyAppName}.ico
SolidCompression=yes
WizardStyle=modern dynamic
ArchiveExtraction=full

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Dirs]
Name: "{app}\actions"
Name: "{app}\graphics"
Name: "{app}\info"
Name: "{app}\lib"
Name: "{app}\ZDoom"
Name: "{app}\ZDoom\IWAD"
Name: "{app}\ZDoom\Map Packs"
Name: "{app}\ZDoom\Mods"
Name: "{app}\ZDoom\Mods\Gameplay"
Name: "{app}\ZDoom\Mods\Graphics"
Name: "{app}\ZDoom\Mods\Music"
Name: "{app}\ZDoom\Mods\Overhaul"
Name: "{app}\ZDoom\gzdoom-4-14-2-windows-External-Pipe"

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "{#MyAppLocalRepository}\src\{#MyAppName}.bat";     DestDir: "{app}"
Source: "{#MyAppLocalRepository}\src\{#MyAppName}_v*.ps1";  DestDir: "{app}"
Source: "{#MyAppLocalRepository}\src\actions\*.psd1";       DestDir: "{app}\actions"; Flags: recursesubdirs createallsubdirs
Source: "{#MyAppLocalRepository}\src\graphics\*.ico";       DestDir: "{app}\graphics"
Source: "{#MyAppLocalRepository}\src\info\*.pdf";           DestDir: "{app}\info"
Source: "{#MyAppLocalRepository}\src\lib\*.ps1";            DestDir: "{app}\lib"

;DoomRunner

;DoomRunner
Source: "https://github.com/Youda008/DoomRunner/releases/download/v1.9.2/DoomRunner-1.9.2-Windows-recent_x86_64-static_exe.zip"; DestDir: "{app}\ZDoom"; DestName: "DoomRunner.zip";  ExternalSize:17_283_005; Flags: external download ignoreversion extractarchive
Source: "{#MyAppLocalRepository}\src\json\DoomRunner\*.json";                                DestDir: "{app}\ZDoom"

;GZDoom
Source: "https://github.com/jeremytiggy/external-pipe/releases/download/v1.2/gzdoom-4-14-2-windows-External-Pipe-complete.7z"; DestDir: "{app}\ZDoom"; DestName:"gzdoom-external-pipe.7z"; ExternalSize:20_769_870; Flags: external download ignoreversion extractarchive recursesubdirs createallsubdirs
;Source: "{#MyAppLocalRepository}\included_repos\JeremyTiggy\external-pipe\gzdoom-4-14-2-windows-External-Pipe\*"; DestDir: "{app}\ZDoom\gzdoom-4-14-2-windows-External-Pipe";       Flags: recursesubdirs createallsubdirs
Source: "{#MyAppLocalRepository}\src\pk3\*.pk3";                                                                  DestDir: "{app}\ZDoom\gzdoom-4-14-2-windows-External-Pipe\addons"

;Internet Archive IWADS
Source: "https://archive.org/download/doom-quickstart-archive-v-2/IWADS/DOOMU.WAD"; DestDir: "{app}\ZDoom\IWAD"; DestName: "DOOM.WAD"; ExternalSize:12_408_292; Flags: external download ignoreversion
Source: "https://archive.org/download/doom-quickstart-archive-v-2/IWADS/DOOM2.WAD"; DestDir: "{app}\ZDoom\IWAD"; DestName: "DOOM2.WAD"; ExternalSize:14_604_584; Flags: external download ignoreversion
Source: "https://archive.org/download/doom-quickstart-archive-v-2/IWADS/doom_complete.pk3"; DestDir: "{app}\ZDoom\IWAD"; DestName: "doom_complete.pk3"; ExternalSize:42_317_867; Flags: external download ignoreversion




[Icons]
;Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{app}\{#MyAppName}";  Filename: "{syswow64}\cmd.exe"; Parameters: "/c {#MyAppExeName}" ;WorkingDir: "{app}"; IconFilename: "{app}\graphics\{#MyAppName}.ico"
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppName}.lnk"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppName}.lnk"; Tasks: desktopicon
Name: "{group}\{#MyAppName} Program Folder"; Filename: "{app}"
Name: "{autodesktop}\{#MyAppName} Program Folder"; Filename: "{app}"; Tasks: desktopicon
Name: "{group}\DoomRunner ({#MyAppName})"; Filename: "{app}\ZDoom\DoomRunner.exe"; WorkingDir: "{app}"
Name: "{autodesktop}\DoomRunner ({#MyAppName})"; Filename: "{app}\ZDoom\DoomRunner.exe"; WorkingDir: "{app}"; Tasks: desktopicon
Name: "{group}\Quick Start Guide"; Filename: "{app}\info\{#MyAppName} Interface Script Quick Start Guide.pdf"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]
;Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -Command ""Set-ExecutionPolicy -Scope CurrentUser Bypass -Force"""; Flags: runhidden

[InstallDelete]
;Type: files; Name:"{app}\ZDoom\DoomRunner.zip"; 