#library "ChatFunctions"
#include "zcommon.acs"

// Format a string to look like a chat message
//add cvar to inherit the text color from the CVAR 
//user 

/*
user bool 					CV_b_CF_Enable_Send = true;
user int					CV_n_CF_Prefix_Style = 1; // 1: "Playername: ", 2: Custom
user string					CV_s_CF_Prefix = "CHAT: ";
*/
function void SB_Chatbot_Send(str string)
{
	if (GetCVAR("CV_b_SB_Chatbot_Enable"))
	{
		// Format with header
		int prefixStyle = GetCVAR("CV_n_SB_Chatbot_Prefix");
		str prefix;
		
		switch (prefixStyle)
		{
			case 1: prefix = StrParam(n:PlayerNumber(),s:": "); break; // 1: Use Player Chat style
			case 2: prefix = GetCVARString("CV_s_SB_Chatbot_Prefix"); break; // 2: Use custom string
			
		}
		str chatbotData = StrParam(s:prefix,s:string);
		// Send
		// Currently, we use the console log file to transmit the data out.
		Log(s:"\c*",s:chatbotData,s:"\c-");
	}
	return;
}
