#library "ShooKrewInteractive"
#include "zcommon.acs"
#include "Databases.acs"


/*CVARs
server noarchive string 	CV_s_TF_categoryId = "categoryId";
server noarchive string 	CV_s_TF_categoryName = "categoryName";
server noarchive string 	CV_s_TF_actionId = "actionId";
server noarchive string 	CV_s_TF_actionName = "Action Name";
server noarchive string 	CV_s_TF_userID = "userID";
server noarchive string 	CV_s_TF_username = "username";
server noarchive string 	CV_s_TF_nickname = "Nick Name";
*/

/*
Current Interface
CV_s_API_summon_username
CV_s_API_summon_classname
CV_b_API_summon_buddy
CV_n_API_summon_size
CV_n_API_summon_points
CV_b_API_dataReady
*/

int n_TF_pointsGameMode; // 1- Basic Point Totals, 2- Bounty Hunt
int n_TF_SummonedPointer;
#define MAX_SUMMONS 30
#define MAX_CHATTERS 40

str s_DB_ChatUsername[MAX_SUMMONS]; //Read from server
str s_DB_ActorClassname[MAX_SUMMONS]; //Read from server
int n_DB_ActorTID[MAX_SUMMONS];
int n_DB_ActorPoints[MAX_SUMMONS]; //Read from server
int n_DB_ActorSizeCategory[MAX_SUMMONS]; //Read from server
int n_DB_ActorAgeTicks[MAX_SUMMONS]; //yet to implement
int f_DB_MarkerOffset[MAX_SUMMONS]; // lookup from actor Size Category
str s_DB_MarkerClassname[MAX_SUMMONS]; //calculated after read
int n_DB_MarkerTID[MAX_SUMMONS];
int n_DB_MarkerAgeTicks[MAX_SUMMONS]; //yet to implement
int n_DB_ActorDistance[MAX_SUMMONS];

bool b_RunTheScript;

function int n_FindActorInSummonsList(int TID)
{
	bool debug = GetCVAR("CV_b_debug");
	bool verbose = GetCVAR("CV_b_verbose") && debug;
	if (verbose) Log(s:"n_FindActorInSummonsList(",d:TID,s:")");
	if (debug) Log(s:"Invalid TID was passed to n_FindActorInSummonsList");
	if (TID <= 0) return -1;													if (verbose) Log(s:"TID=",d:TID);
	for (int m = 1; m < MAX_SUMMONS; m++) {
		if (n_DB_ActorTID[m] == TID) {
			if (verbose) Log(s:"return (",d:m,s:")");
			return m;
		}
	}
	if (verbose) Log(s:"return -1");
	if (debug) Log(s:"TID#",d:TID,s:" was not found in Summons List");
	return -1;
}

function void removeSummonsListEntry(int entrynumber)
{
	bool debug = GetCVAR("CV_b_debug");
	bool verbose = GetCVAR("CV_b_verbose") && debug;
	if (verbose) Log(s:"removeSummonsListEntry(",d:entrynumber,s:")");
	
	if (entrynumber <= 0 || entrynumber > MAX_SUMMONS) {
		if (debug) Log(s:"Invalid Summons List entry marked for deletion");
	return;}
	
	n_db_ActorTID[entrynumber] = -1;
	s_DB_ChatUsername[entrynumber] = ""; 
	s_DB_ActorClassname[entrynumber] = ""; 
	n_DB_ActorPoints[entrynumber] = -1; 
	n_DB_ActorSizeCategory[entrynumber] = -1;
	n_DB_ActorAgeTicks[entrynumber] = -1;
	if (n_DB_MarkerTID[entrynumber] > 0) { Thing_Remove(n_DB_MarkerTID[entrynumber]) ; 				if (verbose) Log(s:"Removing Marker: ",d:n_DB_ActorTID[entrynumber]);  
													n_DB_MarkerTID[entrynumber] = 0;}
	f_DB_MarkerOffset[entrynumber] = -1;
	s_DB_MarkerClassname[entrynumber] = "";
	n_DB_MarkerAgeTicks[entrynumber] = -1;
	if (verbose) Log(s:"return()");
}
function void removeActorFromSummonsList(int TID, bool Remove)
{
	bool debug = GetCVAR("CV_b_debug");
	bool verbose = GetCVAR("CV_b_verbose") && debug;
	if (verbose) Log(s:"removeActorFromSummonsList(",d:TID,s:", ",d:Remove,s:")");
	if (TID <= 0) { if (verbose) Log(s:"TID<=0, return()"); return; }
	int m = n_FindActorInSummonsList(TID);
	if (m < 0) { if (verbose) Log(s:"m<0, return()"); return;}
	if (n_DB_ActorTID[m] > 0 && Remove) { 
		Spawn("TeleportFog", GetActorX(n_DB_ActorTID[m]), GetActorY(n_DB_ActorTID[m]), GetActorZ(n_DB_ActorTID[m]),0);
		Thing_Remove(n_DB_ActorTID[m]); 				if (verbose) Log(s:"Removing Thing: ",d:n_DB_ActorTID[m],s:", ",s:s_DB_ChatUsername[m],s:"'s ",s:s_DB_ActorClassname[m]); 
	}
	removeSummonsListEntry(m);
	if (verbose) Log(s:"return()");
}

function int measureSummonsListEntryDist_WU(int entrynumber)
{
	int actorTID = n_DB_ActorTID[entrynumber];
	if (actorTID <= 0) return 0;

	int actor_x = GetActorX(actorTID);
	int actor_y = GetActorY(actorTID);
	int actor_z = GetActorZ(actorTID);
	int actorXdistance = actor_x - GetActorX(0);
	int actorYdistance = actor_y - GetActorY(0);
	int actorVectorAngle = VectorAngle(actorXdistance,actorYdistance);
	// Since there's a 3D effect to the ground, we have to include that when we consider the distance
	// Since it'll look like it's farther away if it's moving around 
	// The World Units (WU) means that we are in that space.
	int actorDistance_WU;
	if( ( (actorVectorAngle + 0.125) % 0.5) > 0.25) actorDistance_WU = FixedDiv(actorYdistance, sin(actorVectorAngle));
	else actorDistance_WU = FixedDiv(actorXdistance, cos(actorVectorAngle));
	return actorDistance_WU;
}

#include "BetterSpawn.acs"
#include "Persistence.acs"
#include "Helpers.acs"





bool newData_ONS;
bool handshake_ONS;
script 250 ENTER NET {

	// Level starts with 0 summoned creatures
	n_TF_SummonedPointer = 0;
	// FUTURE: different game modes.
	n_TF_pointsGameMode = 1;
	
	// clear new Data Oneshot
	newData_ONS = false;
	
	if (GetCVAR("CV_b_TF_ShowModeAtLevelStart") > 0) ACS_ExecuteWait(673);
	
	while (1 > 0) 
	{
		bool debug = GetCVAR("CV_b_debug");
		bool verbose = GetCVAR("CV_b_verbose") && debug;
		if (verbose) Log(s:"script ShooKrewOpen OPEN NET: each tick");
		
		// Read API_dataReady bit
		// The most important thing that predicates further action is
		// the presence of an actor class name to summon.
		bool classnameNotEmptyOrBlank = false;
		// The data to be collected is:
		str s_TF_sanitized_user; 		// CV_s_API_summon_username 	--> s_TF_sanitized_user			--> s_DB_ChatUsername[]
		str s_TF_summon_classname; 		// CV_s_API_summon_classname --> s_TF_summon_classname 		--> s_DB_ActorClassname[]
		bool allegianceFriendly;		// CV_b_API_summon_buddy			--> allegianceFriendly 			--> MakeBuddy(spawnedActorTID)
		int n_classSize;				// CV_n_API_summon_size 		--> n_classSize 				--> n_DB_ActorSizeCategory[]
		int pointsToUserOnPlayerDeath;  // CV_n_API_summon_points 			--> pointsToUserOnPlayerDeath 	--> n_DB_ActorPoints[]
		
		bool newData = GetCVAR("CV_b_API_dataReady"); //b_RunTheScript;													
		if (verbose) Log(s:"newData: ",d:newData);
		bool readNewData = newData && !newData_ONS;														if (verbose) Log(s:"newData_ONS: ",d:newData_ONS,s:", readNewData: ",d:readNewData);
		bool handshake = newData && newData_ONS;
		//if (handshake && !handshake_ONS) SetCVAR("CV_b_API_dataReady",0);
		handshake_ONS = handshake;																		if (verbose) Log(s:"handshake_ONS: ",d:handshake_ONS,s:", handshake: ",d:handshake);
		if (readNewData)
		{
			// Get all specifics
			// Get Username, either from Tikfinity or other API
			if (GetCVAR("CV_b_TF_nametagTikfinity")) s_TF_sanitized_user = GetCVARString("CV_s_TF_nickname"); 
			else s_TF_sanitized_user = GetCVARString("CV_s_TF_username");						if (verbose) Log (s:"s_TF_sanitized_user: ",s:s_TF_sanitized_user);
			
			bool usernameNotEmpty = (s_TF_sanitized_user != "empty");
			bool usernameNotBlank = (s_TF_sanitized_user != "");
			bool usernameNotEmptyOrBlank = (usernameNotEmpty || usernameNotBlank); 						if (verbose) Log(s:"usernameNotEmptyOrBlank: ",d:usernameNotEmptyOrBlank);
			// Get Actor being summoned, make sure it's not blank
			s_TF_summon_classname = GetCVARString("CV_s_API_summon_classname");							if (verbose) Log(s:"s_TF_summon_classname: ",s:s_TF_summon_classname);
			bool classnameNotEmpty = (s_TF_summon_classname != "empty");
			bool classnameNotBlank = (s_TF_summon_classname != "");
			classnameNotEmptyOrBlank = (classnameNotEmpty || classnameNotBlank);						if (verbose) Log(s:"classnameNotEmptyOrBlank: ",d:classnameNotEmptyOrBlank);
			// Get Actor allegiance
			allegianceFriendly = GetCVAR("CV_b_API_summon_buddy");												if (verbose) Log(s:"allegianceFriendly: ",d:allegianceFriendly);
			// Get listed class Size
			n_classSize = GetCVAR("CV_n_API_summon_size");													if (verbose) Log(s:"n_classSize: ",d:n_classSize);
			// Get listed Points value
			pointsToUserOnPlayerDeath = GetCVAR("CV_n_API_summon_points");										if (verbose) Log(s:"pointsToUserOnPlayerDeath: ", d:pointsToUserOnPlayerDeath);
			// Get listed Tier
			// FUTURE
			if (debug) Log(s:"New Data: ",s:s_TF_sanitized_user,s:"summons a Class ",d:n_classSize,s:" ",s:s_TF_summon_classname,s:" worth ",d:pointsToUserOnPlayerDeath);
		} //end if (newData)
		newData_ONS = newData;
		
		// If the classname isn't empty, than the read was successful
		if (classnameNotEmptyOrBlank)
		{
			// Let's try to spawn the actor.
			int spawnedActorTID = SpawnNearPlayerByClassRadius(s_TF_summon_classname, 0, true);			if (verbose) Log(s:"SpawnNearPlayerByClassRadius(",s:s_TF_summon_classname,s:", 0, true) = ",d:spawnedActorTID);
			bool actorSpawnedOK = spawnedActorTID > 0; 													if (verbose) Log(s:"actorSpawnedOK: ",d:actorSpawnedOK);
			
			// If it wasn't successful, we should let someone know if they're interested
			if (debug && !actorSpawnedOK) Log(s:"WARNING: Unsuccessful Spawn from API request");
			
			// If it was successful, excellent! We have one more thing to track!
			// We will load up our database with as much info as is immediately available
			if (actorSpawnedOK) {
				// Wrap Around the array
				if (n_TF_SummonedPointer + 1 > MAX_SUMMONS)
				{
					n_TF_SummonedPointer = 1;
				}
				else
				{
					n_TF_SummonedPointer++;
				}
				// Initialize the summon slot
				removeSummonsListEntry(n_TF_SummonedPointer);
				// Initialized
				
																										if (verbose) Log(s:"n_TF_SummonedPointer: ",d:n_TF_SummonedPointer);
				n_DB_ActorTID[n_TF_SummonedPointer] = spawnedActorTID;									if (verbose) Log(s:"n_DB_ActorTID[] = ",d:n_DB_ActorTID[n_TF_SummonedPointer]);
				// Assign the user
				s_DB_ChatUsername[n_TF_SummonedPointer] = s_TF_sanitized_user;							if (verbose) Log(s:"s_DB_ChatUsername[] = ",s:s_DB_ChatUsername[n_TF_SummonedPointer]);
				// Update the classname with the exact case match of what was spawned
				s_TF_summon_classname = StrParam(s:GetActorClass(spawnedActorTID));						if (verbose) Log(s:"s_TF_summon_classname: ",s:s_TF_summon_classname);
				s_DB_ActorClassname[n_TF_SummonedPointer] = s_TF_summon_classname;						if (verbose) Log(s:"s_DB_ActorClassname[] = ",s:s_DB_ActorClassname[n_TF_SummonedPointer]);
				// Assign the Sprite size				
				s_DB_MarkerClassname[n_TF_SummonedPointer] = "TikTok_Marker";//s_formTikTokMarkerSprite(n_classSize, allegianceFriendly);												if (verbose) Log(s:"s_DB_MarkerClassname[",d:n_TF_SummonedPointer,s:"]: ",s:s_DB_MarkerClassname[n_TF_SummonedPointer]);
				n_DB_ActorSizeCategory[n_TF_SummonedPointer] = n_classSize;								if (verbose) Log(s:"n_DB_ActorSizeCategory[] = ",d:n_DB_ActorSizeCategory[n_TF_SummonedPointer]);
				str s_offsetCVAR;
				switch (n_classSize) {
					case 1: s_offsetCVAR = "CV_f_TF_overheadMarker_Offset1"; break;
					case 2: s_offsetCVAR = "CV_f_TF_overheadMarker_Offset2"; break;
					case 3: s_offsetCVAR = "CV_f_TF_overheadMarker_Offset3"; break;
					case 4: s_offsetCVAR = "CV_f_TF_overheadMarker_Offset4"; break;
					default: s_offsetCVAR = "CV_f_TF_overheadMarker_Offset1"; break;
				}
				f_DB_MarkerOffset[n_TF_SummonedPointer] = GetCVAR(s_offsetCVAR);						if (verbose) Log(s:"f_DB_MarkerOffset[]: ",f:f_DB_MarkerOffset[n_TF_SummonedPointer]);
				n_DB_MarkerTID[n_TF_SummonedPointer] = -1; //initialize
				// Assign the points
				n_DB_ActorPoints[n_TF_SummonedPointer] = pointsToUserOnPlayerDeath;						if (verbose) Log(s:"n_DB_ActorPoints[] = ",d:n_DB_ActorPoints[n_TF_SummonedPointer]);				
			}

			// Now that the actor is successfully spawned, it will be appropriately made a buddy
			if (actorSpawnedOK && allegianceFriendly) MakeBuddy(spawnedActorTID);
			
			// Database is up to date and actor is spawned
			
		} //end of if (classnameNotEmptyOrBlank)	

		// Every tick, update the nametag display
		ACS_ExecuteWait(251); 																			if (verbose) Log(s:"ACS_ExecuteWait(251);");
		
		delay(1);
	} //end While (1>0)
} // end of Enter Script

// ------------------------------------------------------------
// Nametag Display
// ------------------------------------------------------------
/*

*/
script 251 (void)
{
	bool debug = GetCVAR("CV_b_debug");
	bool verbose = GetCVAR("CV_b_verbose") && debug; 									if (verbose) Log(s:"Script 251: Nametag Display");

	// Read Parameters
	bool    overheadMarkerEnable = GetCVAR("CV_b_TF_overheadMarkerEnable");
	bool	nametagEnable 		= GetCVAR("CV_b_TF_nametagEnable");
	int 	nametagColorFriend	= GetCVAR("CV_n_TF_nametagColorFriend");
	int 	nametagColorFoe		= GetCVAR("CV_n_TF_nametagColorFoe");
	bool	nametagFontAuto		= GetCVAR("CV_b_TF_nametagFontAuto");
	int 	f_fontsize_changePoint_pct = GetCVAR("CV_f_TF_nametagFontAutoSP");
	int 	nametagFont_close = GetCVARString("CV_f_TF_nametagFontAutoClose");
	int 	nametagFont_far 	= GetCVARString("CV_f_TF_nametagFontAutoFar");
	str 	nametagFont_default	= GetCVARString("CV_s_TF_nametagFont");
	int 	f_nametagYoffset_pct = GetCVAR("CV_f_TF_nametagYoffset_pct");
	int 	nametagRange_px 	= GetCVAR("CV_n_TF_nametagRange");
	int		nametagRange_WU		= (nametagRange_px * 1.0);
	int 	markerRange_WU 		= GetCVAR("CV_f_TF_nametagIconRange_WU");
	
	// local nametag & marker database
	// see Databases.acs for more information
	i_db_Size = 0;
	
	// Only process if there are tracked summons to put name tags on
	bool evaluateNametags = nametagEnable && n_TF_SummonedPointer > 0;
	if (evaluateNametags)
	{
		// Check out each summoned actor on the field		
		for (int instance = 1; instance < MAX_SUMMONS; instance++)
		{

			// Load up the TID at that instance
			int  nametagActorTID 		= n_DB_ActorTID[instance];															
			// Check if it's valid.
			bool nametagActorTID_valid 	= nametagActorTID > 0; 																			if (verbose) Log(s:"instance: ",d:instance,s:", nametagActorTID: ",d:n_DB_ActorTID[instance],s:", nametagActorTID_valid: ",d:nametagActorTID_valid);
			// There are a few ways to end things early.
			// Mainly, if either the actor or the player are dead/removed
			bool nametagActorDestroyed 			= false;
			bool nametagActorNotDestroyed 		= false;
			bool nametagActorAlive 				= false;
			bool nametagActorDead	    		= false;
			bool playerLiesDefeatedAndBleeding 	= false;
			bool playerIsAliveAndKickingAss 	= false;
			// If the TID is valid, then we can safely evaluate those properties.
			if (nametagActorTID_valid) {
				nametagActorDestroyed 	=   ThingCount(T_NONE, nametagActorTID) == 0 ;
				nametagActorNotDestroyed = ThingCount(T_NONE, nametagActorTID) > 0;
				nametagActorAlive 		= GetActorProperty(nametagActorTID, APROP_Health) > 0;
				nametagActorDead	    = GetActorProperty(nametagActorTID, APROP_Health) <= 0;
				playerLiesDefeatedAndBleeding = GetActorProperty(0, APROP_Health) <= 0;
				playerIsAliveAndKickingAss = GetActorProperty(0, APROP_Health) > 0;
				if (verbose) Log(s:"nametagActorNotDestroyed: ",d:nametagActorNotDestroyed,s:", nametagActorAlive: ",d:nametagActorAlive,s:", nametagActorTID_valid: ",d:nametagActorTID_valid,s:", playerIsAliveAndKickingAss: ",d:playerIsAliveAndKickingAss);
			}

			// If the actor is not destroyed, is alive, and the player is still alive, then it makes sense to draw it's nametag.
			bool validActor = ( nametagActorNotDestroyed && nametagActorAlive && nametagActorTID_valid && playerIsAliveAndKickingAss);
			// Otherwise, if the actor with the TID we are looking at is destroyed, dead,  
			// then it makes sense to remove that TID from the collection.
			//Game Mode: Shot Clock
			bool actorTooOld;
			if (GetCVAR("CV_b_TF_ShotClock") > 0)
			{
				int n_ShotClock_ticks = GetCVAR("CV_n_TF_ShotClock_Seconds") * 35;
				if (verbose) Log(s:"ShotClock Active. Tick Setpoint: ",d:n_ShotClock_ticks);
				if (n_ShotClock_ticks >= 35) actorTooOld = (n_DB_MarkerAgeTicks[instance] > n_ShotClock_ticks); // 
			}
			
			
			bool cleanupActor = ( nametagActorDestroyed || nametagActorDead || actorTooOld) && nametagActorTID_valid && playerIsAliveAndKickingAss;
																																		if (verbose) Log(s:"validActor: ",d:validActor,s:", cleanupActor: ",d:cleanupActor,s:", actorTooOld: ",d:actorTooOld);
			// Add 1 to it's lifetime counter if it's still valid and not eligible for cleanup
			if (validActor && !cleanupActor) { n_DB_MarkerAgeTicks[instance]++; 											if (verbose) Log(s:"life time: ",d:n_DB_MarkerAgeTicks[instance]); 
												}																																		
			// If the actor needs to be cleaned up, then set its' entries to 0 & ""
			if ( cleanupActor )
			{
				if (verbose) Log(s:"Deleting Invalid Entry: ",d:instance,s:", ",s:s_DB_ChatUsername[instance],s:"'s ",s:n_DB_ActorTID[instance]);
				bool despawnTID = actorTooOld && (GetCVAR("CV_B_TF_ShotClock_Despawn")>0);
				removeActorFromSummonsList(nametagActorTID, despawnTID);
			}
			// If the actor and the player are still around, draw the name tag if possible
			if ( validActor )
			{
				// Next we get a rough estimate of how far away the actor is from the player
				int nametagActorDistance_WU = measureSummonsListEntryDist_WU(instance); 												if (verbose) Log(s:"nametagActorDistance_WU: ",f:nametagActorDistance_WU);
				// So now we determine if the actor is far away enough to either
				// not draw the nametag, or do draw the marker (seperate things)
				bool nametagActorDistanceOK = nametagActorDistance_WU <= nametagRange_WU;
				bool nametagActorDistanceTooFar = nametagActorDistance_WU > nametagRange_WU;
				bool markerActorDDistanceOK = nametagActorDistance_WU >= markerRange_WU;
				bool markerActorDistanceTooClose = nametagActorDistance_WU < markerRange_WU;
				// If the actor is within draw distance, and the nametag and marker are enabled, add it to the draw order
				bool nametagDrawDistanceOK =  nametagActorDistanceOK && nametagEnable;
				bool markerDrawDistanceOK  = markerActorDDistanceOK && overheadMarkerEnable;
				bool drawNametagOrMarker = nametagDrawDistanceOK || markerDrawDistanceOK;
				if (drawNametagOrMarker) {
					i_db_Keys[i_db_Size] = instance;
					i_db_Values[i_db_Size] = nametagActorDistance_WU;
					i_db_Size++; 
					if (verbose) Log(s:"i_db_Keys[",d:i_db_Size-1,s:"]=",d:instance,s:", i_db_Values[",d:i_db_Size-1,s:"]=",f:nametagActorDistance_WU,s:", i_db_Size=",d:i_db_Size);
				}
				
				// We undraw the marker if the markers' actor gets too close,
				// or if the option to draw it is disabled.
				bool undrawOverheadMarker = (markerActorDistanceTooClose || !overheadMarkerEnable) && (n_DB_MarkerTID[instance] > 0); 							if (verbose) Log(s:"undrawOverheadMarker: ",d:undrawOverheadMarker);				
				if (undrawOverheadMarker)
				{
					int removeTID = n_DB_MarkerTID[instance];
					bool markerExistsAtStart = ThingCount(T_NONE,removeTID) > 0; 									if (verbose) Log(s:"ThingCount(T_NONE,",d:removeTID,s:") = ",d:ThingCount(T_NONE,removeTID));
					if (markerExistsAtStart) Thing_Remove(n_DB_MarkerTID[instance]); 									if (verbose) Log(s:"Thing_Remove(",d:removeTID,s:");");
					bool thingRemoved = ThingCount(T_NONE,removeTID) <= 0;
					if (thingRemoved) n_DB_MarkerTID[instance] = -1;							
					if (verbose) Log(s:"markerRemoved: ",d:removeTID);
				}
			} // end of validActor
		} // end for
		
		// Now that we have gone thru andd iterated thru all the main summon instances,
		// check the items we isolated and nominated to draw.
		//evaluate database members
		if (i_db_Size > 0)
		{
			if (verbose) Log(s:"i_db_Size: ",d:i_db_Size);
			//Sort the summons by their distance from the player
			DB_Values_Sort(ORDER_DESCENDING);
			
			// Now find out how many nametags and markers we can render
			int nametagsRenderedCount = 0;
			int markersRenderedCount = 0;
			int nametagsRenderedMax = GetCVAR("CV_n_TF_nametagRenderCtMax");
			if (nametagsRenderedMax > 5) nametagsRenderedMax = 5;
			if (nametagsRenderedMax < 1) nametagsRenderedMax = 1;
			int markersRenderedMax = GetCVAR("CV_n_TF_markerRenderCtMax");
			if (markersRenderedMax > 10) markersRenderedMax = 10;
			if (markersRenderedMax < 1) markersRenderedMax = 1;
			int n_sign = -1;
			if (verbose) Log(s:"nametagsRenderedMax: ",d:nametagsRenderedMax,s:", markersRenderedMax: ",d:markersRenderedMax);
			// go thru the list and draw the nametags and markers 
			for (int rendering = 0; rendering < i_db_Size; rendering++)	{
				int r = i_db_Keys[rendering]; // 'r' is the pointer to thje main data base
				int rTID = n_DB_ActorTID[r]; // rTID is the Actor the nametag/marker is referencing
				int rDist = i_db_Values[rendering];
				if (verbose) Log(s:"rendering: ",d:rendering,s:", r: ",d:i_db_Keys[rendering],s:", rTID: ",d:n_DB_ActorTID[r],s:", rDist: ",d:i_db_Values[rendering]);
				if (verbose) Log(s:"nametagsRenderedCount: ",d:nametagsRenderedCount,s:", markersRenderedCount:",d:markersRenderedCount);
				bool renderNametag = (i_db_Values[rendering] <= nametagRange_WU) && (nametagsRenderedCount < nametagsRenderedMax);
				bool renderMarker =  (i_db_Values[rendering] >= markerRange_WU)  && (markersRenderedCount  < markersRenderedMax);
				if (verbose) Log(s:"renderNametag: ",d:renderNametag,s:", renderMarker: ",d:renderMarker);
				n_sign *= -1;
				
				if (renderMarker) {
					// We check to see if a marker sprite has been generated already for the far away actor
					int markerTIDtoRender = -1;
					int f_markerOffset_extra = 1.0 * rendering * n_sign;
					// If there's no TID for the marker available, make a new marker
					if (n_DB_MarkerTID[r] <= 0) { 
						markerTIDtoRender = UniqueTID(); 
						// try too spawn the marker above the actors' head, which if successful, will return a 1
						int markersSpawned = Spawn("TikTok_Marker", GetActorX(rTID), GetActorY(rTID), GetActorZ(rTID) + f_DB_MarkerOffset[r] + f_markerOffset_extra, markerTIDtoRender); 				if (verbose) Log(s:"Spawn(TikTok_Marker,",f:GetActorX(rTID),s:",",f:GetActorY(rTID),s:",",f:GetActorZ(rTID) + f_DB_MarkerOffset[r] + f_markerOffset_extra,s:",",d:markerTIDtoRender,s:")");
																																							if (verbose) Log(s:"markersSpawned: ",d:markersSpawned);
						bool markerSpawned = markersSpawned > 0;																							if (verbose) Log(s:"markerSpawned: ",d:markerSpawned);					
						if (!markerSpawned) markerTIDtoRender = -1;
							if (verbose) Log(s:"markerSpawned: ",d:markerTIDtoRender);
						n_DB_MarkerTID[r] = markerTIDtoRender;																								if (verbose) Log(s:"new n_DB_MarkerTID[",d:instance,s:"]: ",d:n_DB_MarkerTID[r]);											
					}
					else
					{
						// Move the current marker aroound
						SetActorPosition(n_DB_MarkerTID[r],GetActorX(rTID),GetActorY(rTID),GetActorZ(rTID) + f_DB_MarkerOffset[r] + f_markerOffset_extra,false);					if (verbose) Log(s:"SetActorPosition(",d:n_DB_MarkerTID[r],s:",",f:GetActorX(rTID),s:",",f:GetActorY(rTID),s:",",f:GetActorZ(rTID) + f_DB_MarkerOffset[r] + f_markerOffset_extra,s:",",d:false,s:");");						
					} if (verbose) Log(s:"n_DB_MarkerTID: ",d:n_DB_MarkerTID[r]);					
					
					markersRenderedCount++;
				} // end of renderMarker
				
				if (renderNametag)	{
					// To keep us from having to track the unique tid of the message, we just use a formula.
					
					int f_nametagOffset_extra = 0.06 * rendering;
					str nametagUsername 		= s_DB_ChatUsername[r];
					int nametagMessageID		= rTID + 1000;																								if (verbose) Log(s:"nametagUsername: ",s:nametagUsername,s:", nametagMessageID: ",d:nametagMessageID);
					
					// Choose the proper color code for the nametag based on allegiance
					
					bool nametagFriendly = GetActorProperty(rTID, APROP_Friendly);
					str FriendFoe;
					if (nametagFriendly) {FriendFoe = "Friend";} else {FriendFoe = "Foe";}
					str nametagColorCVAR = StrParam(s:"CV_n_TF_nametagColor",s:FriendFoe,d:nametagsRenderedCount+1);
					int nametagColor = GetCVAR(nametagColorCVAR);
					if (verbose) Log(s:"nametagFriendly: ",d:nametagFriendly,s:", nametagColor: ",d:nametagColor);

					// Nametag Font selection
					str nametagFont;
					// One option we have is to change between a large font and a small font based on how far
					// Away the actor is from the player. This adds a depth illusion.
					if (nametagFontAuto)
					{
						// The point at which the change happens is user selected		
						int f_fontsize_changePoint_WU = f_fontsize_changePoint_pct * nametagRange_px;					if (verbose) Log(s:"f_fontsize_changePoint_pct: ",f:f_fontsize_changePoint_pct,s:", f_fontsize_changePoint_WU: ",f:f_fontsize_changePoint_WU);
						bool nametagActorDistanceClose = rDist < f_fontsize_changePoint_WU; 			if (verbose) Log(s:"nametagActorDistanceClose: ",d:nametagActorDistanceClose);					
						if (nametagActorDistanceClose) nametagFont = nametagFont_close; else nametagFont = nametagFont_far;
					} 																									
					// Otherwise, we go with the default option.
					if (!nametagFontAuto) nametagFont = nametagFont_default; 											if (verbose) Log(s:"nametagFontAuto: ",d:nametagFontAuto,s:", nametagFont: ",s:nametagFont); 
					
					// Draw the Nametag on the actor now that the font has been picked.								
					HudMessageOnActorNew(
						rTID,
						nametagMessageID,
						0, // int n_SetHudSize_X_px
						0, // int n_SetHudSize_Y_px
						0.0, // int f_Text_XOffsetPct
						f_nametagYoffset_pct + f_nametagOffset_extra, //int f_Text_YOffsetPct
						nametagRange_px, // int n_DrawDistanceMax_px
						nametagFont, // str s_fontname,
						false, //bool b_sprite
						nametagUsername, // str s_text
						0, //int n_holdTime_ticks
						nametagColor // int n_HudMsg_Color_CR
						); 																									if (verbose) Log(s:"rTID: ",d:rTID,s:", nametagMessageID: ",d:nametagMessageID,s:", f_nametagYoffset_pct: ",d:f_nametagYoffset_pct,s:", nametagRange_px: ",d:nametagRange_px,s:", nametagUsername: ",s:nametagUsername,s:", nametagColor: ",d:nametagColor);

					
					nametagsRenderedCount++;
				}// end if (nametagsRenderedCount <= nametagsRenderedMax)
			}// end for rendering
		} // end if (i_db_Size > 0)
	}// end if evaluateNametags
}// end script Nametag Display


// ------------------------------------------------------------
// Obituary
// ------------------------------------------------------------
// Identify Killer & Display Obituary Message
script 252 DEATH NET 
{
	
	bool debug = GetCVAR("CV_b_debug");
	bool verbose = GetCVAR("CV_b_verbose") && debug; 								if (verbose) Log(s:"script 252 DEATH NET");
	

	
	// Get the TID of the thing that killed the player
	int targetTID = GetActorProperty(0,APROP_TargetTID);
		bool validTargetTID = targetTID > 0;										if (verbose) { Log(s:"Target TID: ",d:targetTID,s:", valid:",d:validTargetTID); }
	
	// Find if it exists in the list of Summoned Monsters
	// If it does, then it is the killer.
	int summonedIndex = n_FindActorInSummonsList(targetTID);						if (verbose) Log(s:"summonedIndex = ",d:summonedIndex); 
	bool summonedMobKilledPlayer = summonedIndex > 0; 								if (verbose) Log(s:"summonedMobKilledPlayer=",d:summonedMobKilledPlayer);
	
	// If a summoned monster didn't kill the player, then just skip the rest
	//if (!summonedMobKilledPlayer) return;
	
	// If a Summoned Mob killed the player, get the specifics of the summoned mob
	if (summonedMobKilledPlayer)
	{
		int summonedTID = targetTID; 												if (verbose) Log(s:"summonedTID = ",d:targetTID); 
		str summonedClass = StrParam(s:GetActorClass(summonedTID));					if (verbose) Log(s:"summonedClass=",s:summonedClass);
		str summonerName = s_DB_ChatUsername[summonedIndex]; 						if (verbose) Log(s:"summonedName = ",s:summonerName); 
		bool summonedBuddy = GetActorProperty(summonedTID,APROP_Friendly) > 0;		if (verbose) Log(s:"summonedBuddy=",d:summonedBuddy);
		int summonedPointValue = n_DB_ActorPoints[summonedIndex];				if (verbose) Log(s:"summonedPointValue=",d:summonedPointValue);;

		
		
		// If the summon was a buddy, then the players death is Friendly Fire
		bool friendlyFire = summonedBuddy; 											if (verbose) Log(s:"friendlyFire=",d:friendlyFire);
		
		// If the summoners' name isn't blank, then we can properly credit them with the  kill
		bool playerKillerKnown = summonedMobKilledPlayer && (summonerName != "");	if (verbose) Log(s:"playerKillerKnown=",d:playerKillerKnown);
		
		// But we do not give points to buddy-kills
		bool shameBuddySlayer = playerKillerKnown && friendlyFire;
		if (shameBuddySlayer) Log(s:"\cd",s:summonerName,s:"'s\c- ",s:GetActorClass(targetTID),s:" \cdfailed their ally\c- ",n:0,s:".");

		//But that won't ever happen, right?
		bool scoreSummonerKill = playerKillerKnown && !friendlyFire;				if (verbose) Log(s:"scoreSummonerKill=",d:scoreSummonerKill);
		
		// Check the game mode, and give points accordingly.
		int pointsAwarded = 0;
		
		// Basic Points: API sends point values, stores in database.
		bool awardBasicPoints = scoreSummonerKill && (n_TF_pointsGameMode == 1);	if (verbose) Log(s:"awardBasicPoints=",d:awardBasicPoints);
		if (awardBasicPoints)
		{
			pointsAwarded = summonedPointValue;
			awardUserPoints(summonerName, pointsAwarded);
		}
		
		// Advanced Gamemodes - Coming Soon!
		
		
		// If it was a scoring event, then display the appropriate messages
		if (pointsAwarded > 0)
		{
			// Build display messages for scoring event
			if (GetCVAR("CV_b_TF_PrintObitMessage"))
			{
				str basicPointsMessage = StrParam(	s:"\cx",s:summonerName,s:"\c-",
												s:" ",s:s_randomVerbed(),s:" ",n:0,
												s:" with their ",s:"\cx",s:GetActorClass(targetTID),s:".",s:"\c-",
												s:" \cd +",d:pointsAwarded,s:"\c- points");
				Print(s:basicPointsMessage);
			}
			
			if (GetCVAR("CV_b_SB_AnnounceObitToChatbot"))
			{
				str chatbotMessage = StrParam(s:summonerName,s:" ",s:s_randomVerbed(),s:" ",s:"me with their ",s:summonedClass);
				SB_Chatbot_Send(chatbotMessage);
			}	
		}
		
		// Display Obituary on Players' Screen
		bool obituaryEnabled = GetCVAR("CV_b_TF_obituaryEnable");
		bool displayObituary = obituaryEnabled && !friendlyFire;
		if (displayObituary)
		{
			str obituaryText = StrParam(s:summonerName,s:"\n \n \n+",d:pointsAwarded,s:" points");
			int obituaryID = targetTID + 2000;
			int obituaryHUDcolor = GetCVAR("CV_n_TF_obituaryHUDcolor");
			int f_obituaryX = GetCVAR("CV_f_TF_obituaryX");
			int f_obituaryY = GetCVAR("CV_f_TF_obituaryY");
			int f_obituaryHoldTime = GetCVAR("CV_f_TF_obituaryHoldTime");
			int f_obituaryTypeTime = GetCVAR("CV_f_TF_obituaryTypeTime");
			int f_obituaryFadeTime = GetCVAR("CV_f_TF_obituaryFadeTime");
			str obituaryFont = GetCVARString("CV_s_TF_obituaryFont");
			SetFont(obituaryFont);
																							if (verbose) Log(s:"HUDMessage(",s:obituaryText,s:"; HUDMSG_TYPEON, ",d:obituaryID,s:", ",d:obituaryHUDcolor,s:", ",f:f_obituaryX,s:", ",f:f_obituaryY,s:", ",f:f_obituaryHoldTime,s:", ",f:f_obituaryTypeTime,s:", ",f:f_obituaryFadeTime,s:");");
			HUDMessage(s:obituaryText; HUDMSG_TYPEON, obituaryID, obituaryHUDcolor, f_obituaryX, f_obituaryY, f_obituaryHoldTime, f_obituaryTypeTime, f_obituaryFadeTime);	
		} //end obituary
	
	} // end if (summonedMobKilledPlayer)
		
} // end of script

SCRIPT 253 (void)
{
	Log(s:"Purging Heretics...");
	for (int i = 0;  i  < MAX_SUMMONS; i++) {
		removeSummonsListEntry(i);
	}
	Log(s:"...Done.");
}
SCRIPT 254 (void)
{
	Log(s:"Purging Heretics...");
	for (int i = 0;  i  < MAX_SUMMONS; i++) {
		int tid = n_DB_ActorTID[i]; Log(s:"Entry: ",d:i,s:", TID: ",d:tid);
		if (n_DB_ActorTID[i] > 0) { removeActorFromSummonsList(tid, true); }
		else { removeSummonsListEntry(i); }
	}
	Log(s:"...Done.");
}

SCRIPT 255 (void)
{
	Log(s:"Summoning Monster");
	b_RunTheScript = true;
}